[workspace]
members = [
    "core/goldsrc-sys",
    "core/goldsrc-api",
    "backends/goldsrc-metamod",
    "backends/goldsrc-wasm-host",
    "framework/goldsrc",
    "framework/goldsrc-macros",
    "examples/demo_plugins/vip_core",
    "examples/demo_plugins/vip_menu",
    "examples/demo_plugins/test_suite",
    "examples/demo_plugins/admin_system",
]
default-members = [
    "core/goldsrc-sys",
    "core/goldsrc-api",
    "backends/goldsrc-metamod",
    "backends/goldsrc-wasm-host",
    "framework/goldsrc",
    "framework/goldsrc-macros",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ulquiorracode/GoldSrc.rs"

[workspace.dependencies]
goldsrc-sys = { path = "core/goldsrc-sys", version = "0.1.0" }
goldsrc-api = { path = "core/goldsrc-api", version = "0.1.0" }
goldsrc-metamod = { path = "backends/goldsrc-metamod", version = "0.1.0" }
goldsrc-wasm-host = { path = "backends/goldsrc-wasm-host", version = "0.1.0" }
goldsrc = { path = "framework/goldsrc", version = "0.1.0" }
goldsrc-macros = { path = "framework/goldsrc-macros", version = "0.1.0" }
wasmtime = { version = "47.0", default-features = false, features = [
    "cranelift",
    "pulley",
    "component-model",
    "runtime",
    "std",
] }
wit-bindgen = "0.60.0"
wit-component = "0.256.0"
wit-parser = "0.256.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
lexopt = "0.3"

[profile.release]
lto = "fat"
opt-level = "z"
strip = "debuginfo"
panic = "abort"
codegen-units = 1
