use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir.parent().unwrap();

    let hlsdk = repo_root.join("references").join("hlsdk");
    let metamod = repo_root
        .join("private")
        .join("references")
        .join("metamod-r")
        .join("metamod")
        .join("extra")
        .join("example")
        .join("include")
        .join("metamod");

    // Check that references exist
    if !hlsdk.join("engine").join("eiface.h").exists() {
        panic!(
            "\n\nERROR: HLSDK not found at {}\n\
             Run the setup script first:\n\
               pwsh scripts/setup.ps1        (Windows)\n\
               bash scripts/setup.sh         (Linux/macOS)\n\n",
            hlsdk.display()
        );
    }

    if !metamod.join("meta_api.h").exists() {
        panic!(
            "\n\nERROR: metamod-r not found at {}\n\
             Run the setup script first:\n\
               pwsh scripts/setup.ps1        (Windows)\n\
               bash scripts/setup.sh         (Linux/macOS)\n\n",
            metamod.display()
        );
    }

    // Read build config (generated by setup script)
    let config_path = repo_root.join(".build-config.toml");
    let config = if config_path.exists() {
        std::fs::read_to_string(&config_path).expect("Failed to read .build-config.toml")
    } else {
        String::new()
    };

    let mut includes: Vec<String> = Vec::new();

    // HLSDK includes
    for dir in &["public", "engine", "common", "dlls"] {
        includes.push(format!("-I{}", hlsdk.join(dir).display()));
    }

    // Metamod includes
    let metamod_parent = metamod.parent().unwrap().parent().unwrap();
    includes.push(format!("-I{}", metamod_parent.display()));
    includes.push(format!("-I{}", metamod.display()));

    // System includes from config
    for line in config.lines() {
        let line = line.trim();
        if line.starts_with("include_path") {
            let path = line.splitn(2, '=').nth(1).unwrap_or("").trim().trim_matches('"');
            if !path.is_empty() {
                includes.push(format!("-I{}", path));
            }
        }
    }

    let includes_ref: Vec<&str> = includes.iter().map(|s| s.as_str()).collect();

    let bindings = bindgen::Builder::default()
        .header(manifest_dir.join("wrapper.h").to_str().unwrap())
        .clang_args(&includes_ref)
        .allowlist_function(".*")
        .allowlist_type(".*")
        .allowlist_var(".*")
        .generate()
        .expect("Unable to generate bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
