[package]
name = "goldsrc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Public framework (SDK) for GoldSrc.rs plugin developers"

[dependencies]
goldsrc-sys = { workspace = true }
goldsrc-api = { workspace = true }
goldsrc-wasm-host = { workspace = true, optional = true }
goldsrc-macros = { workspace = true }
lexopt = { workspace = true, optional = true }

[features]
# Enable the host-side management runtime and CLI.
host = ["goldsrc-wasm-host"]
host-cli = ["host", "lexopt"]
