[package]
name = "goldsrc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Public framework (SDK) for GoldSrc.rs plugin developers"

[dependencies]
goldsrc-sys = { workspace = true }
goldsrc-api = { workspace = true }
goldsrc-wasm-host = { workspace = true, optional = true }
goldsrc-macros = { workspace = true }
