[package]
name = "goldsrc-metamod"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Metamod backend implementation for GoldSrc.rs"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0"

[dependencies]
goldsrc-sys = { workspace = true }
goldsrc-api = { workspace = true }
goldsrc-wasm-host = { workspace = true }
lexopt = "0.3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Memory", "Win32_Foundation"] }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"
