#!/usr/bin/env bash
# GoldSrc.rs — Reference Setup Script
#
# Clones all required reference repositories for building the project.
# Detects system SDK paths and writes them to .build-config.toml.
# Run this once after cloning the repo:
#
#   bash scripts/setup.sh         # Linux/macOS
#   pwsh scripts/setup.ps1        # Windows
#
# Options:
#   -f, --force    Re-clone even if directory exists

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
REFS_DIR="$REPO_ROOT/references"
PRIVATE_REFS_DIR="$REPO_ROOT/private/references"

FORCE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force) FORCE=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

declare -A REPOS=(
    ["hlsdk"]="https://github.com/alliedmodders/hlsdk.git"
    ["rehlds"]="https://github.com/s1lentq/ReHLDS.git"
    ["metamod-r"]="https://github.com/theAsmodai/metamod-r.git"
    ["goldsrcmod-net"]="https://github.com/DrAbcOfficial/GoldSrcMod.Net.git"
)

# Create directories
mkdir -p "$REFS_DIR" "$PRIVATE_REFS_DIR"

# Clone references
for name in "${!REPOS[@]}"; do
    url="${REPOS[$name]}"

    case "$name" in
        hlsdk) path="$REFS_DIR/hlsdk" ;;
        *)     path="$PRIVATE_REFS_DIR/$name" ;;
    esac

    if [[ -d "$path" ]]; then
        if $FORCE; then
            echo "  [FORCE] Removing existing $name..."
            rm -rf "$path"
        else
            echo "  [SKIP] $name already exists at $path"
            continue
        fi
    fi

    echo "  [CLONE] $name from $url..."
    git clone --depth 1 "$url" "$path"
    echo "  [OK] $name cloned successfully"
done

# Clean up unnecessary directories to save space
echo ""
echo "Cleaning up unnecessary directories..."

# HLSDK: only need engine/, public/, common/, dlls/ for bindgen
for dir in cl_dll dmc ricochet utils dedicated game_shared linux network pm_shared third_party; do
    full_path="$REFS_DIR/hlsdk/$dir"
    if [[ -d "$full_path" ]]; then
        rm -rf "$full_path"
        echo "  [REMOVED] hlsdk/$dir"
    fi
done

# metamod-r: only need metamod/extra/example/include/
metamod_path="$PRIVATE_REFS_DIR/metamod-r"
if [[ -d "$metamod_path" ]]; then
    for dir in metamod/src metamod/plugins metamod/build metamod/build_64 metamod/build_64_opt metamod/build_opt metamod/buildbot metamod/docs metamod/extra/example/src metamod/extra/example/Makefile metamod/extra/readme.txt metamod/README.md metamod/LICENSE; do
        full_path="$metamod_path/$dir"
        if [[ -d "$full_path" ]]; then
            rm -rf "$full_path"
            echo "  [REMOVED] metamod-r/$dir"
        fi
    done
fi

# Detect system SDK paths
echo ""
echo "Detecting system SDK paths..."

CONFIG_LINES=()

# On Linux, we need clang headers (usually provided by clang package)
if command -v clang &>/dev/null; then
    echo "  [FOUND] clang: $(command -v clang)"
    # clang usually finds its own headers, but we can add explicit paths if needed
fi

# On macOS, we might need Xcode Command Line Tools
if [[ "$(uname)" == "Darwin" ]]; then
    if xcode-select -p &>/dev/null; then
        echo "  [FOUND] Xcode CLI tools: $(xcode-select -p)"
    fi
fi

# Write config
config_path="$REPO_ROOT/.build-config.toml"
cat > "$config_path" << EOF
# GoldSrc.rs build configuration
# Generated by scripts/setup.sh — do not edit manually.
# This file is gitignored — each developer runs setup on their own machine.

EOF

for line in "${CONFIG_LINES[@]}"; do
    echo "$line" >> "$config_path"
done

echo ""
echo "Build config written to $config_path"
echo ""
echo "Setup complete. You can now run: cargo build --target i686-unknown-linux-gnu"
