# GoldSrc.rs — Reference Setup Script
#
# Clones all required reference repositories for building the project.
# Detects system SDK paths and writes them to .build-config.toml.
# Run this once after cloning the repo:
#
#   pwsh scripts/setup.ps1        # Windows
#   bash scripts/setup.sh         # Linux/macOS

param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$RefsDir = Join-Path $RepoRoot "references"
$PrivateRefsDir = Join-Path $RepoRoot "private\references"

function Test-Reference {
    param([string]$Path)
    return (Test-Path (Join-Path $Path ".git")) -or (Test-Path $Path)
}

# Create directories
New-Item -ItemType Directory -Force -Path $RefsDir | Out-Null
New-Item -ItemType Directory -Force -Path $PrivateRefsDir | Out-Null

# Clone references
$Repos = @(
    @{ Name = "hlsdk";             Url = "https://github.com/alliedmodders/hlsdk.git";      Path = Join-Path $RefsDir "hlsdk" },
    @{ Name = "rehlds";            Url = "https://github.com/s1lentq/ReHLDS.git";            Path = Join-Path $PrivateRefsDir "rehlds" },
    @{ Name = "metamod-r";         Url = "https://github.com/theAsmodai/metamod-r.git";      Path = Join-Path $PrivateRefsDir "metamod-r" },
    @{ Name = "goldsrcmod-net";    Url = "https://github.com/DrAbcOfficial/GoldSrcMod.Net.git"; Path = Join-Path $PrivateRefsDir "goldsrcmod-net" }
)

foreach ($Repo in $Repos) {
    $name = $Repo.Name
    $url = $Repo.Url
    $path = $Repo.Path

    if (Test-Reference $path) {
        if ($Force) {
            Write-Host "  [FORCE] Removing existing $name..."
            Remove-Item -Recurse -Force $path
        } else {
            Write-Host "  [SKIP] $name already exists at $path"
            continue
        }
    }

    Write-Host "  [CLONE] $name from $url..."
    git clone --depth 1 $url $path
    if ($LASTEXITCODE -ne 0) { Write-Error "Failed to clone $name" }
    Write-Host "  [OK] $name cloned successfully"
}

# Detect system SDK paths
Write-Host ""
Write-Host "Detecting system SDK paths..."

$ConfigLines = @()

# Windows SDK
$WinSdkBasePath = "C:\Program Files (x86)\Windows Kits\10\Include"
if (Test-Path $WinSdkBasePath) {
    $WinSdkVersion = (Get-ChildItem $WinSdkBasePath -Directory | Sort-Object Name -Descending | Select-Object -First 1).Name
    if ($WinSdkVersion) {
        $WinSdkPath = Join-Path $WinSdkBasePath $WinSdkVersion
        Write-Host "  [FOUND] Windows SDK $WinSdkPath"
        foreach ($dir in @("ucrt", "shared", "um")) {
            $fullPath = Join-Path $WinSdkPath $dir
            if (Test-Path $fullPath) {
                $ConfigLines += "include_path = `"$fullPath`""
            }
        }
    }
} else {
    Write-Host "  [WARN] Windows SDK not found at $WinSdkBasePath"
}

# MSVC
$MsvcBasePath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC"
if (Test-Path $MsvcBasePath) {
    $MsvcVersion = (Get-ChildItem $MsvcBasePath -Directory | Sort-Object Name -Descending | Select-Object -First 1).Name
    if ($MsvcVersion) {
        $MsvcPath = Join-Path $MsvcBasePath $MsvcVersion
        Write-Host "  [FOUND] MSVC $MsvcPath"
        foreach ($dir in @("include", "atlmfc\include")) {
            $fullPath = Join-Path $MsvcPath $dir
            if (Test-Path $fullPath) {
                $ConfigLines += "include_path = `"$fullPath`""
            }
        }
    }
} else {
    Write-Host "  [WARN] MSVC not found at $MsvcBasePath"
}

# LLVM (for bindgen)
$LlvmPath = "C:\Program Files\LLVM\bin"
if (Test-Path $LlvmPath) {
    Write-Host "  [FOUND] LLVM $LlvmPath"
    $ConfigLines += "llvm_path = `"$LlvmPath`""
} else {
    Write-Host "  [WARN] LLVM not found at $LlvmPath"
}

# Write config
$configContent = @"
# GoldSrc.rs build configuration
# Generated by scripts/setup.ps1 — do not edit manually.
# This file is gitignored — each developer runs setup on their own machine.

"@

foreach ($line in $ConfigLines) {
    $configContent += "$line`n"
}

$configPath = Join-Path $RepoRoot ".build-config.toml"
Set-Content -Path $configPath -Value $configContent -NoNewline
Write-Host ""
Write-Host "Build config written to $configPath"

Write-Host ""
Write-Host "Setup complete. You can now run: cargo build --target i686-pc-windows-msvc"
