[package]
name = "goldsrc-metamod-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Metamod backend implementation for GoldSrc.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
goldsrc-sys = { workspace = true }
goldsrc-api = { workspace = true }
