[package]
name = "test_suite"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ECS, entity inspection, sound playback, and CVar test suite"


[lib]
crate-type = ["cdylib"]

[dependencies]
goldsrc = { workspace = true }
